
import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author a37104
 */
public class Casino extends javax.swing.JFrame {

    boolean inCasino = false;
    
    /**
     * Creates new form Casino
     */
    public Casino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spFichasApostar = new javax.swing.JSpinner();
        ckAllIn = new javax.swing.JCheckBox();
        sdNumero = new javax.swing.JSlider();
        btnApostar = new javax.swing.JButton();
        lbNumero = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();
        btnx2 = new javax.swing.JButton();
        btnMetade = new javax.swing.JButton();
        btnMais10 = new javax.swing.JButton();
        btnMais100 = new javax.swing.JButton();
        btnMenos10 = new javax.swing.JButton();
        btnMenos100 = new javax.swing.JButton();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDepositar = new javax.swing.JButton();
        spFichas = new javax.swing.JSpinner();
        btnSair = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel5.setText("jLabel5");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo Do Dado"));

        jLabel7.setText("Fichas a apostar:");

        jLabel6.setText("Número a apostar:");

        spFichasApostar.setEnabled(false);

        ckAllIn.setText("Apostar Tudo");
        ckAllIn.setEnabled(false);
        ckAllIn.setOpaque(false);
        ckAllIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckAllInActionPerformed(evt);
            }
        });

        sdNumero.setMajorTickSpacing(1);
        sdNumero.setMaximum(6);
        sdNumero.setMinimum(1);
        sdNumero.setMinorTickSpacing(1);
        sdNumero.setPaintLabels(true);
        sdNumero.setPaintTicks(true);
        sdNumero.setSnapToTicks(true);
        sdNumero.setValue(1);
        sdNumero.setEnabled(false);
        sdNumero.setOpaque(false);

        btnApostar.setText("Apostar");
        btnApostar.setEnabled(false);
        btnApostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApostarActionPerformed(evt);
            }
        });

        lbNumero.setBackground(new java.awt.Color(102, 204, 255));
        lbNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNumero.setText("O número do dado que saiu foi:");
        lbNumero.setOpaque(true);

        lbResultado.setBackground(new java.awt.Color(0, 255, 0));
        lbResultado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbResultado.setForeground(new java.awt.Color(255, 255, 255));
        lbResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbResultado.setText("Perdeu Ou Ganhou");
        lbResultado.setOpaque(true);

        btnx2.setText("x2");
        btnx2.setEnabled(false);
        btnx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx2ActionPerformed(evt);
            }
        });

        btnMetade.setText("1/2");
        btnMetade.setEnabled(false);
        btnMetade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetadeActionPerformed(evt);
            }
        });

        btnMais10.setText("+10");
        btnMais10.setEnabled(false);
        btnMais10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMais10ActionPerformed(evt);
            }
        });

        btnMais100.setText("+100");
        btnMais100.setEnabled(false);
        btnMais100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMais100ActionPerformed(evt);
            }
        });

        btnMenos10.setText("-10");
        btnMenos10.setEnabled(false);
        btnMenos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenos10ActionPerformed(evt);
            }
        });

        btnMenos100.setText("-100");
        btnMenos100.setEnabled(false);
        btnMenos100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenos100ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnApostar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMenos100)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMenos10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnx2)
                                .addGap(14, 14, 14)
                                .addComponent(btnMetade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMais10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMais100)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spFichasApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ckAllIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sdNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spFichasApostar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckAllIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnx2)
                    .addComponent(btnMetade)
                    .addComponent(btnMais10)
                    .addComponent(btnMais100)
                    .addComponent(btnMenos10)
                    .addComponent(btnMenos100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(sdNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Casino");
        jLabel2.setOpaque(true);

        jLabel3.setText("Nome:");

        jLabel4.setText("Fichas:");

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnSair.setText("Fim do jogo");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spFichas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDepositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tfNome)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepositar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        depositar();
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostarActionPerformed
        apostar();
    }//GEN-LAST:event_btnApostarActionPerformed

    private void ckAllInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckAllInActionPerformed
        if (ckAllIn.isSelected()){
            allIn();
        }
    }//GEN-LAST:event_ckAllInActionPerformed

    private void btnMetadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetadeActionPerformed
        int mais = (int) spFichasApostar.getValue();
        mais /= 2;
        spFichasApostar.setValue(mais);
    }//GEN-LAST:event_btnMetadeActionPerformed

    private void btnx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx2ActionPerformed
        int mais = (int) spFichasApostar.getValue();
        mais *= 2;
        spFichasApostar.setValue(mais);
    }//GEN-LAST:event_btnx2ActionPerformed

    private void btnMenos100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenos100ActionPerformed
        int mais = (int) spFichasApostar.getValue();
        if (mais>=100){
            mais -= 100;
        }else{
            mais = 0;
        }
        spFichasApostar.setValue(mais);
    }//GEN-LAST:event_btnMenos100ActionPerformed

    private void btnMenos10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenos10ActionPerformed
        int mais = (int) spFichasApostar.getValue();
        if (mais>=10){
            mais -= 10;
        }else{
            mais = 0;
        }
        spFichasApostar.setValue(mais);
    }//GEN-LAST:event_btnMenos10ActionPerformed

    private void btnMais10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMais10ActionPerformed
        int mais = (int) spFichasApostar.getValue() + 10;
        if((int) spFichas.getValue() >= mais){
            spFichasApostar.setValue(mais);
        }else{
            allIn();
        }
    }//GEN-LAST:event_btnMais10ActionPerformed

    private void btnMais100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMais100ActionPerformed
        int mais = (int) spFichasApostar.getValue() + 100;
        if((int) spFichas.getValue() >= mais){
            spFichasApostar.setValue(mais);
        }else{
            allIn();
        }
    }//GEN-LAST:event_btnMais100ActionPerformed

    private void apostar(){
        if ((int) spFichas.getValue() > 0){
            if((int) spFichas.getValue() >= (int) spFichasApostar.getValue()){
                if ((int) spFichasApostar.getValue()>0){
                    rodarDado();
                }
            }else{
                allIn();
                rodarDado();
            }
        }else{
            inCasino = false;
            desativar();
        }
    }
    
    private void rodarDado(){
        int dinheiro = (int) spFichas.getValue();
        int apostado = (int) spFichasApostar.getValue();
        
        int dado = (int) (Math.random() * 6) + 1;
        int numeroApostado = (int) sdNumero.getValue();
        
        if (dado==numeroApostado){
            //Ganhou
            dinheiro += apostado;
            spFichas.setValue(dinheiro);
            
            lbNumero.setText("Saiu o número: " + Integer.toString(dado));
            lbResultado.setText("Ganhou");
            lbResultado.setBackground(Color.GREEN);
        }else{
            //Perdeu
            dinheiro -= apostado;
            spFichas.setValue(dinheiro);
            
            lbNumero.setText("Saiu o número: " + Integer.toString(dado));
            lbResultado.setText("Perdeu");
            lbResultado.setBackground(Color.RED);
        }
        
        if ((int) spFichas.getValue() == 0){
            inCasino = false;
            desativar();
        }
        
        ckAllIn.setSelected(false);
    }
    
    private void allIn(){
        spFichasApostar.setValue(spFichas.getValue());
    }
    
    private void depositar(){
        if (!tfNome.getText().equals("") && (int) spFichas.getValue() > 0){
            inCasino = true;
            desativar();
        }
    }
    
    private void desativar(){
        if (inCasino){
            //Desativa Parte de Cima
            tfNome.setEnabled(false);
            spFichas.setEnabled(false);
            btnDepositar.setEnabled(false);
            
            //Ativa Parte de Baixo
            spFichasApostar.setEnabled(true);
            ckAllIn.setEnabled(true);
            sdNumero.setEnabled(true);
            btnApostar.setEnabled(true);
            
            btnMetade.setEnabled(true);
            btnx2.setEnabled(true);
            btnMenos100.setEnabled(true);
            btnMenos10.setEnabled(true);
            btnMais100.setEnabled(true);
            btnMais10.setEnabled(true);
        }else{
            //Desativa Parte de Cima
            tfNome.setEnabled(true);
            spFichas.setEnabled(true);
            btnDepositar.setEnabled(true);
            
            //Ativa Parte de Baixo
            spFichasApostar.setEnabled(false);
            ckAllIn.setEnabled(false);
            sdNumero.setEnabled(false);
            btnApostar.setEnabled(false);
            
            btnMetade.setEnabled(false);
            btnx2.setEnabled(false);
            btnMenos100.setEnabled(false);
            btnMenos10.setEnabled(false);
            btnMais100.setEnabled(false);
            btnMais10.setEnabled(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Casino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Casino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Casino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Casino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Casino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApostar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnMais10;
    private javax.swing.JButton btnMais100;
    private javax.swing.JButton btnMenos10;
    private javax.swing.JButton btnMenos100;
    private javax.swing.JButton btnMetade;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnx2;
    private javax.swing.JCheckBox ckAllIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JSlider sdNumero;
    private javax.swing.JSpinner spFichas;
    private javax.swing.JSpinner spFichasApostar;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
