import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tiago Severino
 */
public class JogoDoGaloForm extends javax.swing.JFrame {
    
    String[][] tabela = new String[3][3];
    String jogador = "X";
    String bot = "O";
    
    boolean isBot = false;
    boolean isFinished = false;
    
    int scoreBot = 0;
    int scoreJogador = 0;
    int nrJogada = 0;

    /**
     * Creates new form JogoDoGaloForm
     */
    public JogoDoGaloForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lbResultado = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo Do Galo");
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        btn00.setFont(new java.awt.Font("Courier New", 0, 72)); // NOI18N
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });
        jPanel1.add(btn00);

        btn01.setFont(new java.awt.Font("Courier New", 0, 72)); // NOI18N
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        jPanel1.add(btn01);

        btn02.setFont(new java.awt.Font("Courier New", 0, 72)); // NOI18N
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });
        jPanel1.add(btn02);

        btn10.setFont(new java.awt.Font("Courier New", 0, 72)); // NOI18N
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPanel1.add(btn10);

        btn11.setFont(new java.awt.Font("Courier New", 0, 72)); // NOI18N
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        jPanel1.add(btn11);

        btn12.setFont(new java.awt.Font("Courier New", 0, 72)); // NOI18N
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        jPanel1.add(btn12);

        btn20.setFont(new java.awt.Font("Courier New", 0, 72)); // NOI18N
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        jPanel1.add(btn20);

        btn21.setFont(new java.awt.Font("Courier New", 0, 72)); // NOI18N
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        jPanel1.add(btn21);

        btn22.setFont(new java.awt.Font("Courier New", 0, 72)); // NOI18N
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });
        jPanel1.add(btn22);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lbResultado.setText("Resultado Bot: 0 Jogador: 0");

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(btnReiniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(lbResultado)
                    .addComponent(btnReiniciar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        jogada(0,0);
    }//GEN-LAST:event_btn00ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        jogada(0,1);
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        jogada(0,2);
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        jogada(1,0);
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        jogada(1,1);
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        jogada(1,2);
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        jogada(2,0);
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        jogada(2,1);
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        jogada(2,2);
    }//GEN-LAST:event_btn22ActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        reinicia();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void jogada(int l, int c){
        if (!isFinished){
            if (tabela[l][c]==null){
                nrJogada++;
                tabela[l][c]=turno();
                desenha(l,c);
                ifGanhou();
                mudaTurno();
            }else{
                if(!cheio()){
                    voltaJogar();
                }
            }
        }
    }
    
    private void updateScore(){
        lbResultado.setText("Resultado Bot: " + scoreBot + " Jogador: " + scoreJogador);
    }
    
    private void botJoga(){
        if(!isFinished){
            if(jogadaRacional()){
                
            }else{
                jogaAoCalhas();
            }
        }
    }
    
    private void jogaAoCalhas(){
        if (tabela[1][1]==null){
            jogada(1, 1);
        }else{
            if(!jogaCanto()){
                int l = (int) (Math.random()*3);
                int c = (int) (Math.random()*3);
                jogada(l, c);
            }
        }
    }
    
    private boolean jogaCanto(){
        if (tabela[0][0]==null){
            jogada(0, 0);
            return true;
        }else{
            if (tabela[0][2]==null){
                jogada(0, 2);
                return true;
            }else{
                if (tabela[2][0]==null){
                    jogada(2, 0);
                    return true;
                }else{
                    if (tabela[2][2]==null){
                        jogada(2, 2);
                        return true;
                    }
                }
            }
        }
        
        return false;
    }
    
    private void jogaMeioCantos(){
        if (tabela[0][1]==null){
            jogada(0, 1);
            return;
        }else{
            if (tabela[1][2]==null){
                jogada(1, 2);
                return;
            }else{
                if (tabela[2][1]==null){
                    jogada(2, 1);
                    return;
                }else{
                    if (tabela[1][0]==null){
                        jogada(1, 0);
                        return;
                    }
                }
            }
        }
    }
    
    private boolean jogadaRacional(){
        
        boolean racional = false;
        String verifica="";
        
        for (int cont=0;cont<2;cont++){
            
            if(cont==0){
                verifica=bot;
            }else{
                verifica=jogador;
            }
            
            for(int i = 0; i<tabela.length; i++){
                //Horizontal

                //Verifica X-Null-X
                if(tabela[i][0]==verifica && tabela[i][1]==null && tabela[i][2]==verifica){
                    jogada(i, 1);
                    return true;
                }
                //Verifica X-X-Null
                if(tabela[i][0]==verifica && tabela[i][1]==verifica && tabela[i][2]==null){
                    jogada(i, 2);
                    return true;
                }
                //Verifica Null-X-X
                if(tabela[i][0]==null && tabela[i][1]==verifica && tabela[i][2]==verifica){
                    jogada(i, 0);
                    return true;
                }

                
                //Vertical

                //Verifica X-Null-X
                if(tabela[0][i]==verifica && tabela[1][i]==null && tabela[2][i]==verifica){
                    jogada(1, i);
                    return true;
                }
                //Verifica X-X-Null
                if(tabela[0][i]==verifica && tabela[1][i]==verifica && tabela[2][i]==null){
                    jogada(2, i);
                    return true;
                }
                //Verifica Null-X-X
                if(tabela[0][i]==null && tabela[1][i]==verifica && tabela[2][i]==verifica){
                    jogada(0, i);
                    return true;
                }
            }

            //Verifica Por Diagonal 1,1
            if(tabela[0][0]==null && tabela[1][1]==verifica && tabela[2][2]==verifica){
                jogada(0, 0);
                return true;
            }

            //Verifica Por Diagonal 1,2
            if(tabela[0][0]==verifica && tabela[1][1]==null && tabela[2][2]==verifica){
                jogada(1, 1);
                return true;
            }

            //Verifica Por Diagonal 1,3
            if(tabela[0][0]==verifica && tabela[1][1]==verifica && tabela[2][2]==null){
                jogada(2, 2);
                return true;
            }


            //Verifica Por Diagonal 2,1
            if(tabela[0][2]==null && tabela[1][1]==verifica && tabela[2][0]==verifica){
                jogada(0, 2);
                return true;
            }

            //Verifica Por Diagonal 2,2
            if(tabela[0][2]==verifica && tabela[1][1]==null && tabela[2][0]==verifica){
                jogada(1, 1);
                return true;
            }

            //Verifica Por Diagonal 2,3
            if(tabela[0][2]==verifica && tabela[1][1]==verifica && tabela[2][0]==null){
                jogada(2, 0);
                return true;
            }
        }
        
        if (nrJogada==3){
            jogaMeioCantos();
            return true;
        }
        
        return racional;
    }
    
    private void ifGanhou(){
        
        for(int i = 0; i<tabela.length; i++){
            //Verifica Por Linhas
            if(tabela[i][0]==turno() && tabela[i][1]==turno() && tabela[i][2]==turno()){
                ganhou();
            }
            //Verifica Por Colunas
            if(tabela[0][i]==turno() && tabela[1][i]==turno() && tabela[2][i]==turno()){
                ganhou();
            }
        }
        
        //Verifica Por Diagonal 1
            if(tabela[0][0]==turno() && tabela[1][1]==turno() && tabela[2][2]==turno()){
                ganhou();
            }
            
            //Verifica Por Diagonal 2
            if(tabela[0][2]==turno() && tabela[1][1]==turno() && tabela[2][0]==turno()){
                ganhou();
            }
    }
    
    private void ganhou(){
        isFinished = true;
        if(turno()==bot){
            scoreBot++;
            JOptionPane.showMessageDialog(null, "Perdeu!");
        }else{
            scoreJogador++;
            JOptionPane.showMessageDialog(null, "Ganhou!");
        }
        updateScore();
    }
    
    private void voltaJogar(){
        if (isBot){
            botJoga();
        }
    }
    
    private void mudaTurno(){
        if(isBot){
            isBot=false;
        }else{
            isBot=true;
            botJoga();
        }
    }
    
    private void desenha(int l, int c){
        if (l==0){
            if (c==0){
                btn00.setText(tabela[l][c]);
            }else{
                if (c==1){
                    btn01.setText(tabela[l][c]);
                }else{
                    if (c==2){
                        btn02.setText(tabela[l][c]);
                    }
                }
            }
        }else{
            if (l==1){
                if (c==0){
                    btn10.setText(tabela[l][c]);
                }else{
                    if (c==1){
                        btn11.setText(tabela[l][c]);
                    }else{
                        if (c==2){
                            btn12.setText(tabela[l][c]);
                        }
                    }
                }
            }else{
                if (l==2){
                    if (c==0){
                        btn20.setText(tabela[l][c]);
                    }else{
                        if (c==1){
                            btn21.setText(tabela[l][c]);
                        }else{
                            if (c==2){
                                btn22.setText(tabela[l][c]);
                            }
                        }
                    }
                }
            }
        }
    }

    private String turno(){
        String joga = "";
        
        if(isBot){
            joga = bot;
        }else{
            joga = jogador;
        }
        
        return joga;
    }
    
    private boolean cheio(){
        for(int i = 0; i<tabela.length; i++){
            for(int c = 0; c<tabela[0].length; c++){
                if (tabela[i][c]==null){
                    return false;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Empate!");
        reinicia();
        return true;
    }
    
    private void reinicia(){
        btn00.setText("");
        btn01.setText("");
        btn02.setText("");
        btn10.setText("");
        btn11.setText("");
        btn12.setText("");
        btn20.setText("");
        btn21.setText("");
        btn22.setText("");
        
        isBot = false;
        isFinished = false;
        nrJogada = 0;
        
        //scoreBot = 0;
        //scoreJogador = 0;
        
        for(int i=0;i<tabela.length;i++){
            for(int c=0;c<tabela.length;c++){
                tabela[i][c]=null;
            }
        }
        
        updateScore();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDoGaloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDoGaloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDoGaloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDoGaloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDoGaloForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbResultado;
    // End of variables declaration//GEN-END:variables
}
